### ISSUE TITLE
(epic) Convert to use sitegen instead

### ISSUE THREAD

**Issue by perlun** [perlun/halleluja.nu#38]
`sitegen` is a new static site generator I have been hacking on during the last few months. It is still its infancy, but if you are curious, the code is available at https://github.com/perlun/sitegen

Some of the features implemented so far are:

- [x] Config file in `.yaml` format. I played around with `.toml` in the beginning since I happen to belive that YAML is a bad idea. Unfortunately, there aren't that many great TOML parsers in .NET either, and the prime candidate has a maintainer that [decided to completely drop TOML as a configuration format](https://github.com/paiden/Nett/issues/91#issuecomment-617864775). Using YAML, as much as I dislike the format, is the simpler option here. YAML support was added in https://github.com/perlun/sitegen/commit/9d49598fcaef33b4a61a976b4402a33936a8d9ae.

- [x] Converting Markdown documents to HTML. Implemented in https://github.com/perlun/sitegen/commit/756e994a2c5d2157721a398fb79154ce21c23ed1 and https://github.com/perlun/sitegen/pull/4

- [x] Produce a listing of blog posts on the front page. Implemented as of https://github.com/perlun/sitegen/pull/4.

- [x] "Watch" support, rebuilding files on demand as they are modified. Works, but using a rather clumsy approach for now. Long-term solution described here: https://github.com/perlun/sitegen/issues/34

**Comment by perlun** [comment]
This went live about 27 days ago, with https://github.com/perlun/halleluja.nu/commit/c8a841dbbc95dae9442307179b681b4a5820e088 and https://github.com/perlun/halleluja.nu/commit/c9fba992b8eb662f52b5710cf82666eed17d464e. :tada: Closing.
